modLoader="javafml"
loaderVersion="[47,)"
license="MIT, CC0 (see LICENSE)"
issueTrackerURL="https://github.com/North-Western-Development/OpenComputers-1.20.1-port/issues"

[[mods]]
modId="opencomputers"
version="${version}"
displayName="OpenComputers"
displayURL="https://oc.cil.li/"
logoFile="pack.png"
credits="Inspired by a couple of other mods, most notably ComputerCraft."
authors="Sangar, Vexatos, payonel, magik6k, Lord Joda and Github Contributors"
description='''This mod adds modular computers and robots that can be programmed in Lua.'''

[[dependencies.opencomputers]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opencomputers]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcversion}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.opencomputers]]
    modId="architectury"
    mandatory=true
    versionRange="[9.2.14,)"
    ordering="AFTER"
    side="BOTH"
