minecraft.version=1.19.2
minecraft.mappings_channel=official
minecraft.mappings_version=1.19.2
forge.version=43.5.0

mod.name=OpenComputers
mod.group=li.cil.oc
mod.version=1.8.5-snapshot

ae2.version=12.9.12
cct.version=1.100.5
jei.version=11.8.1.1034
mekanism.version=1.19.2-10.3.9.13
ccl.version=1.19.2-4.3.2.490
cbmultipart.version=1.19.2-3.2.0.139
casm.version=3.2.0.17
enderstorage.version=1.19.2-2.10.1.181
