org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
enabled_platforms=fabric,forge

archives_base_name=OpenComputers
mod_id=opencomputers
mod_version=1.8.0-snapshot
maven_group=li.cil.oc

architectury_version=9.2.14
fabric_loader_version=0.16.14
fabric_api_version=0.92.12+1.20.1
forge_version=1.20.1-47.4.26

# Lua runtimes (OpenComputers' patched forks).
luaj_version=20220907.1
jnlua_version=20220928.1
typesafe_config_version=1.4.3

# Optional energy interop on Fabric (Team Reborn Energy API).
tr_energy_version=3.0.0
