package li.cil.oc.common;

import com.google.gson.JsonObject;
import li.cil.oc.Settings;
import net.minecraft.advancements.CriteriaTriggers;
import net.minecraft.advancements.critereon.AbstractCriterionTriggerInstance;
import net.minecraft.advancements.critereon.ContextAwarePredicate;
import net.minecraft.advancements.critereon.DeserializationContext;
import net.minecraft.advancements.critereon.ItemPredicate;
import net.minecraft.advancements.critereon.SerializationContext;
import net.minecraft.advancements.critereon.SimpleCriterionTrigger;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;

/**
 * The 1.12 achievements live on as data driven advancements in
 * {@code data/opencomputers/advancements} (generated by tools/advancements.py).
 * Most of them use the vanilla {@code minecraft:inventory_changed} trigger
 * (obtaining the item); the ones that were awarded for assembling something
 * (robot, drone, tablet, microcontroller) use the {@code opencomputers:assembled}
 * criterion fired from {@link #onAssemble}. {@code opencomputers:crafted} is
 * fired from {@link #onCraft} for crafting conditions.
 */
public final class Achievement {
    public static final ItemTrigger ASSEMBLED = new ItemTrigger(new ResourceLocation(Settings.resourceDomain, "assembled"));
    public static final ItemTrigger CRAFTED = new ItemTrigger(new ResourceLocation(Settings.resourceDomain, "crafted"));

    private static boolean registered = false;

    public static synchronized void init() {
        if (registered) return;
        registered = true;
        CriteriaTriggers.register(ASSEMBLED);
        CriteriaTriggers.register(CRAFTED);
    }

    public static void onAssemble(ItemStack stack, Player player) {
        if (player instanceof ServerPlayer serverPlayer && stack != null && !stack.isEmpty()) {
            ASSEMBLED.trigger(serverPlayer, stack);
        }
    }

    public static void onCraft(ItemStack stack, Player player) {
        if (player instanceof ServerPlayer serverPlayer && stack != null && !stack.isEmpty()) {
            CRAFTED.trigger(serverPlayer, stack);
        }
    }

    /** Criterion with an optional {@code "item"} predicate, matched against the assembled / crafted stack. */
    public static final class ItemTrigger extends SimpleCriterionTrigger<ItemTrigger.Instance> {
        private final ResourceLocation id;

        ItemTrigger(ResourceLocation id) {
            this.id = id;
        }

        @Override
        public ResourceLocation getId() {
            return id;
        }

        @Override
        protected Instance createInstance(JsonObject json, ContextAwarePredicate player, DeserializationContext context) {
            return new Instance(id, player, ItemPredicate.fromJson(json.get("item")));
        }

        public void trigger(ServerPlayer player, ItemStack stack) {
            trigger(player, instance -> instance.item.matches(stack));
        }

        public static final class Instance extends AbstractCriterionTriggerInstance {
            private final ItemPredicate item;

            Instance(ResourceLocation id, ContextAwarePredicate player, ItemPredicate item) {
                super(id, player);
                this.item = item;
            }

            @Override
            public JsonObject serializeToJson(SerializationContext context) {
                final JsonObject json = super.serializeToJson(context);
                json.add("item", item.serializeToJson());
                return json;
            }
        }
    }

    private Achievement() {
    }
}
